### ISSUE TITLE
你好，请不要将DH DNS信息发布在公开配置中

### ISSUE THREAD

**Issue by whalesnitch** [shidahuilang/langlang#1]
请删除一下您配置文件中的加密dns，就是这个dh-dns，这个虽然是公益，但是群内提供者没有允许公开，更没有说过开放至公开github。如要在配置文件中引用，可以尝试一下gist的私人库，在保证您的隐私的同时也能继续使用下去，我们也欢迎守规矩的使用者继续使用我们的加密dns

**Comment by shidahuilang** [comment]
已删除
