### ISSUE TITLE
你好，请不要将DH DNS信息发布在公开配置中

### ISSUE THREAD

**Issue by ghost** [shidahuilang/langlang#2]
请将dh dns信息从公开配置中去除，谢谢。
https://github.com/shidahuilang/langlang/blob/1a9497c25aa2625fd0bd4c07c3ed42c23778e3b3/build/Lede_source/files/etc/config/AdGuardHome.yaml
https://github.com/shidahuilang/langlang/blob/fb36f5c457744294cb31cda0aa8891945838f544/build/Lede_nanopi_r2s/files/etc/config/AdGuardHome.yaml
https://github.com/shidahuilang/langlang/blob/fb36f5c457744294cb31cda0aa8891945838f544/build/Lede_nanopi_r4s/files/etc/config/AdGuardHome.yaml

**Comment by shidahuilang** [comment]
OK，已删除
